// This file is generated by scripts/i18n-keys.js
// Do not edit this file directly.
/* eslint-disable */
export const I18N_KEYS = {
  "home": "home",
  "hello": "hello",
  "common": {
    "search": "common.search",
    "noData": "common.noData",
    "actions": "common.actions",
    "view": "common.view",
    "edit": "common.edit",
    "delete": "common.delete",
    "add": "common.add",
    "save": "common.save",
    "cancel": "common.cancel",
    "confirm": "common.confirm",
    "jumpTo": "common.jumpTo",
    "all": "common.all",
    "createdTime": "common.createdTime",
    "id": "common.id",
    "icon": "common.icon",
    "title": "common.title",
    "close": "common.close",
    "confirmDelete": "common.confirmDelete",
    "deleteSuccess": "common.deleteSuccess",
    "deleteFail": "common.deleteFail",
    "addSuccess": "common.addSuccess",
    "addFail": "common.addFail",
    "editSuccess": "common.editSuccess",
    "editFail": "common.editFail",
    "saveSuccess": "common.saveSuccess",
    "saveFail": "common.saveFail",
    "formInvalid": "common.formInvalid",
    "updatedTime": "common.updatedTime",
    "pageNotFound": "common.pageNotFound"
  },
  "login": {
    "username": "login.username",
    "email": "login.email",
    "password": "login.password",
    "login": "login.login",
    "logout": "login.logout",
    "usernamePlaceholder": "login.usernamePlaceholder",
    "emailPlaceholder": "login.emailPlaceholder",
    "passwordPlaceholder": "login.passwordPlaceholder"
  },
  "systemLogs": {
    "actionUserName": "systemLogs.actionUserName",
    "targetName": "systemLogs.targetName",
    "actionType": "systemLogs.actionType",
    "startDate": "systemLogs.startDate",
    "endDate": "systemLogs.endDate"
  },
  "systemRole": {
    "name": "systemRole.name",
    "nameValue": "systemRole.nameValue",
    "isSystem": "systemRole.isSystem",
    "isSystemDesc": "systemRole.isSystemDesc",
    "menuPermission": "systemRole.menuPermission",
    "menuPermissionConfig": "systemRole.menuPermissionConfig"
  },
  "systemUser": {
    "roleId": "systemUser.roleId",
    "none": "systemUser.none",
    "realName": "systemUser.realName",
    "email": "systemUser.email",
    "lastLoginTime": "systemUser.lastLoginTime",
    "gender": "systemUser.gender",
    "role": "systemUser.role",
    "phoneNumber": "systemUser.phoneNumber",
    "avatar": "systemUser.avatar",
    "select": "systemUser.select",
    "emailConfirmed": "systemUser.emailConfirmed",
    "phoneNumberConfirmed": "systemUser.phoneNumberConfirmed",
    "twoFactorEnabled": "systemUser.twoFactorEnabled",
    "lockoutEnd": "systemUser.lockoutEnd",
    "lockoutEnabled": "systemUser.lockoutEnabled",
    "accessFailedCount": "systemUser.accessFailedCount",
    "retryCount": "systemUser.retryCount"
  },
  "language": "language",
  "validation": {
    "required": "validation.required",
    "minlength": "validation.minlength",
    "maxlength": "validation.maxlength",
    "email": "validation.email"
  },
  "menu": {
    "business": "menu.business",
    "customer": "menu.customer",
    "team": "menu.team",
    "product": "menu.product",
    "order": "menu.order",
    "system": "menu.system",
    "systemRole": "menu.systemRole",
    "systemUser": "menu.systemUser",
    "systemLogs": "menu.systemLogs",
    "systemConfig": "menu.systemConfig"
  }
};
